log:
  name: "mnist_classification"
  experiment_name: 'mnist_basicCnn_v00'
  log_dir: '/home/baha/codes/clean_mnist'
  frequency:
    iteration: 1
  root:

checkpoint:
  init: null
  frequency:
    epoch: 1

#############

data:
  train_dir: '/home/baha/codes/clean_mnist/train'
  val_dir: '/home/baha/codes/clean_mnist/test'
  batch_size: 32
  num_workers: 2

  preprocessing:
    mean: 0.1306604
    std:  0.3081078

train:
  epoch: 90
  loss:
  weight: null
  number_class: 10

  optim:
    method: SGD
    lr: 0.1
    weight_decay: 0.0001
    momentum: 0.9

  model:
    model_name: cnn  # cnn
    prtrained: null # 'cifar100'


scheduler:
  method: MultiStepLR
  step_size: [30, 60, 80]
  gamma: 0.1
